version: "3.8"
services:
  postgres:
    image: postgres:15.3-bullseye
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: app_db
    ports:
      - "9095:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
  user_postgres_data:

